name: debugger-action
on: 
  push:
    branches:
      - main
  watch:
    types: started
  schedule:
    - cron: "0 0,6,12,18,21 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup Debug Session
       uses: csexton/debugger-action@master
